version: '3'

services:
  frontend-home:
    container_name: pancake-frontend
    image: "registry-server:5000/pancake-frontend"
    ports:
      - "8033:80"
    environment:
      REACT_APP_BASE_URL: https://citrus-api.sotatek.works
    volumes:
      - ./pancake-frontend:/app
